apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: dev
  labels:
    app: movie-db
spec:
  ports:
    - port: 5432
  selector:
    app: movie-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: dev
  labels:
    app: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: movie_db
            - name: POSTGRES_USER
              value: movie_user
            - name: POSTGRES_PASSWORD
              value: movie_password
          ports:
            - containerPort: 5432
              name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: dev
  labels:
    app: cast-db
spec:
  ports:
    - port: 5432
  selector:
    app: cast-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  namespace: dev
  labels:
    app: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: cast_db
            - name: POSTGRES_USER
              value: cast_user
            - name: POSTGRES_PASSWORD
              value: cast_password
          ports:
            - containerPort: 5432
              name: postgres
